name: 'Assets'

on:
  create:
  pull_request:
  push:
    branches:
      - '[0-9]+.[0-9]+.x'
      - 'refs/pull/*'

jobs:
  webpack:
    name: 'Build Assets'

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608" # v4

      - name: "Using Node"
        uses: "actions/setup-node@v4.0.0"

      - name: "Install dependencies"
        run: "yarn --cwd assets"

      - name: "Build"
        run: "yarn --cwd assets build"

      - name: "Test"
        run: "yarn --cwd assets test"

      - name: "Lint"
        run: "yarn --cwd assets check-lint"

      - name: "Format"
        run: "yarn --cwd assets check-format"

      - name: "Check size"
        run: "yarn --cwd assets size"
